"""add tags

Revision ID: 42fd194829af
Revises: ed6302d93f90
Create Date: 2026-07-28 09:29:51.357213

"""
import sqlmodel
from sqlmodel import SQLModel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42fd194829af'
down_revision: Union[str, Sequence[str], None] = 'ed6302d93f90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Enum('EXPRESS', 'STANDARD', 'FRAGILE', 'HEAVY', 'INTERNATIONAL', 'DOMESTIC', 'TEMPERATURE_CONTROLLED', 'GIFT', 'RETURN', 'DOCUMENTS', name='tagname'), nullable=False),
    sa.Column('instruction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipment_tag',
    sa.Column('shipment_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('shipment_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipment_tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
