"""add shipment event table

Revision ID: 84e60a2d7e76
Revises: c2e4cf771ead
Create Date: 2026-07-26 09:25:39.768557

"""
import sqlmodel
from sqlmodel import SQLModel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84e60a2d7e76'
down_revision: Union[str, Sequence[str], None] = 'c2e4cf771ead'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller', sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('seller', sa.Column('zip_code', sa.Integer(), nullable=True))
    op.drop_column('shipment', 'status')
    op.add_column('shipment_event', sa.Column('location', sa.Integer(), nullable=False))
    op.add_column('shipment_event', sa.Column('status', sa.Enum('placed', 'in_transit', 'out_for_delivery', 'delivered', name='shipmentstatus'), nullable=False))
    op.add_column('shipment_event', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('shipment_event', sa.Column('shipment_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'shipment_event', 'shipment', ['shipment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shipment_event', type_='foreignkey')
    op.drop_column('shipment_event', 'shipment_id')
    op.drop_column('shipment_event', 'description')
    op.drop_column('shipment_event', 'status')
    op.drop_column('shipment_event', 'location')
    op.add_column('shipment', sa.Column('status', postgresql.ENUM('placed', 'in_transit', 'out_for_delivery', 'delivered', name='shipmentstatus'), autoincrement=False, nullable=False))
    op.drop_column('seller', 'zip_code')
    op.drop_column('seller', 'address')
    # ### end Alembic commands ###
