"""add user email verified

Revision ID: de96992ab250
Revises: e6cd52f6f327
Create Date: 2026-07-27 15:15:47.380042

"""
import sqlmodel
from sqlmodel import SQLModel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de96992ab250'
down_revision: Union[str, Sequence[str], None] = 'e6cd52f6f327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_partner', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('seller', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.alter_column('shipment', 'client_contact_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipment', 'client_contact_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('seller', 'email_verified')
    op.drop_column('delivery_partner', 'email_verified')
    # ### end Alembic commands ###
