"""add review

Revision ID: ed6302d93f90
Revises: de96992ab250
Create Date: 2026-07-27 20:54:53.858443

"""
import sqlmodel
from sqlmodel import SQLModel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed6302d93f90'
down_revision: Union[str, Sequence[str], None] = 'de96992ab250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('delivery_partner', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('reviews', sa.Column('rating', sa.Integer(), nullable=False))
    op.add_column('reviews', sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('reviews', sa.Column('shipment_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'reviews', 'shipment', ['shipment_id'], ['id'])
    op.alter_column('seller', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('seller', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'shipment_id')
    op.drop_column('reviews', 'comment')
    op.drop_column('reviews', 'rating')
    op.alter_column('delivery_partner', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
